# Generated by Django 5.1.6 on 2025-03-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book'), ('can_change_book', 'Can edit book details'), ('can_delete_book', 'Can delete a book'), ('can_view_book', 'Can view book details')]},
        ),
    ]
